spring:
  datasource:
    url: jdbc:mysql://120.79.7.246:3306/homework
    username: root
    password: root

  redis:
    sentinel:
      master: mymaster
      nodes: 47.106.38.101:26379,47.106.38.101:26380